## What is scikit-learn (sklearn)?
* It's a machine learning package for python.
* It's built on numpy, scipy and matplotlib.
    * It's fast and efficient.
    * It prefers working with arrays.
* Advantages:
    * Incredible documentations
    * Variety
        * Regression
        * Classification
        * Clustering
        * Support vector machines
        * Dimensionality reduction
    * Numerical stability
* Disadvantages: Deep learning where there are much better packages like tensorflow, keras and pytorch.


# Linear regression with sklearn


In [2]:
# import relevant libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [3]:
# loading data
data = pd.read_csv('8.2 1.01. Simple linear regression.csv')
data.head()

SAT   GPA
0  1714  2.40
1  1664  2.52
2  1760  2.54
3  1685  2.74
4  1693  2.83

In [4]:
# declare dependent and independent Variables
# in supervied-learning we're dealing with futures and targets
x = data['SAT'] # input(feature)
y = data['GPA'] # output(target)
x.shape, y.shape

((84,), (84,))

In [5]:
# sklearn doesn't work with 1D models
# so we should reshape our dataframe to a matrix
x_matrix = x.values.reshape(-1, 1)
x_matrix.shape

(84, 1)

In [6]:
# regression itself
reg = LinearRegression()
reg.fit(x_matrix, y)

LinearRegression()

In [7]:
# R-squared
reg.score(x_matrix, y)

0.40600391479679765

In [8]:
# coefficient
reg.coef_ # this results in an array and in multiple regression models there is other coefficients

array([0.00165569])

In [9]:
# intercept
reg.intercept_

0.27504029966028076

In [10]:
# making predictions
reg.predict(np.array(1740).reshape(-1, 1))

array([3.15593751])

# Multiple regression with sklearn

In [11]:
# loading data
data = pd.read_csv('3.2 1.02. Multiple linear regression.csv')
data.head

<bound method NDFrame.head of      SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
..   ...   ...         ...
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]>

In [12]:
# defining dependent and independent variables
y = data['GPA']
x = data[['SAT', 'Rand 1,2,3']]

In [13]:
# creating a multiple regression model
reg = LinearRegression()
reg.fit(x, y)

LinearRegression()

In [14]:
reg.score(x, y), reg.coef_, reg.intercept_

(0.4066811952814283, array([ 0.00165354, -0.00826982]), 0.29603261264909486)

* Formula for Adj R-squared:
* $R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$


In [15]:
r2 = reg.score(x, y)
n = x.shape[0]
p = x.shape[1]
adjusted_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)
adjusted_r2

0.3920313482513401

* Feature selection simplifies models by removing unneeded variables.
    * This process improves speed and prevents a series of unwanted issues arising from having too many features.

In [16]:
# feature selection with sklearn
from sklearn.feature_selection import f_regression
f_regression(x, y)
# this will create two arrays:
# the first contains f-statistics for each of the regressions
# the second corresponding p-values

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [17]:
f_statistics = f_regression(x, y)[0]
p_values = f_regression(x, y)[1]
f_statistics.round(3), p_values.round(3)

(array([56.048,  0.176]), array([0.   , 0.676]))

## Creating a summary table

In [18]:
reg_summary = pd.DataFrame(data=x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [19]:
reg_summary['coefficients'] = reg.coef_
reg_summary['p_values'] = p_values.round(3)
reg_summary

Features  coefficients  p_values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

## Feature scaling (standardization)
* The common problem when working with numeric data is difference in magnitudes.
    * An easy fix for this issue is standardization. (feature scaling)
        * Standardization is the process of transforming the data we're working with into a standard scale.
        * (x-mean) / std

In [20]:
# importing relevant module and creating an object
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [21]:
scaler.fit(x) # fit calculates and stores the standard deviation of each feature
# scaler contains all standardization info

StandardScaler()

In [22]:
x_scaled = scaler.transform(x)
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

* Regression with scaled features

In [23]:
reg.fit(x_scaled, y)
reg.coef_, reg.intercept_

(array([ 0.17181389, -0.00703007]), 3.330238095238095)

In [24]:
reg_summary = pd.DataFrame(data=[['intercept (bias)'], ['SAT'], ['Rand 1,2,3']], columns=['Features'])
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]
reg_summary

Features   Weights
0  intercept (bias)  3.330238
1               SAT  0.171814
2        Rand 1,2,3 -0.007030

## Making predictions with the standardized coefficients (weights)

In [25]:
new_data = pd.DataFrame(data=[[1700, 2], [1800, 1]], columns=['SAT', 'Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [26]:
reg.predict(new_data)
# this results in wrong output because we didn't standardized the input

C:\Users\ShayanJul\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([295.39979563, 312.58821497])

In [27]:
# so we should scale our data with the info that already is in scaler
new_data_scaled = scaler.transform(new_data)
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

## Underfitting and Overfitting
* Overfitting means that our training has focused on the particular training data set so much, it has "missed the point"
    * The problem is that random noise is captured inside an overfitted model.
    * Overfitting is hard to spot because the accuracy of the model seems outstanding.
    * The solution is to split the initial dataset into two. training and test
        * Because the model has never seen the test data set it can't overfit on it.
* Underfitting means that the model has not captured the underlying logic of the data.
    * Underfitted models have low accuracy. It means there are no relationships to be found or we need a different model.
    * Underfitting is easy to spot.

In [28]:
# importing related modules
from sklearn.model_selection import train_test_split

In [30]:
# creating two arrays for splitting the data
a = np.arange(1, 101)
b = np.arange(501, 601)
a, b

(array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100]),
 array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
        514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
        527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
        540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
        553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
        566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 5

In [46]:
# splitting the data
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size=0.2, shuffle=False, random_state=42)
# default test size is 25%
# shuffle is True by default and in practice, most of the times we want to shuffle the data
# Without setting a random_state value we'll get a different subsets each time we split the data
# a and b elements are shuffled in the same way

In [45]:
# exploring the results
a_train.shape, a_test.shape, a_train, a_test

((80,),
 (20,),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
        69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80]),
 array([ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]))

In [47]:
b_train.shape, b_test.shape, b_train, b_test

((80,),
 (20,),
 array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
        514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
        527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
        540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
        553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
        566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
        579, 580]),
 array([581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593,
        594, 595, 596, 597, 598, 599, 600]))